[versions]
kotlin = "2.3.0"
cmp = "1.10.0"

[libraries]

[plugins]
org-jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
org-jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "cmp" }
